;;; fzf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fzf.el

(autoload 'fzf "fzf" "\
Starts a fzf session." t)
(autoload 'fzf-directory "fzf" "\
Starts a fzf session at the specified directory.

(fn DIRECTORY)" t)
(register-definition-prefixes "fzf" '("fzf/"))

;;; End of scraped data

(provide 'fzf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fzf-autoloads.el ends here
