;;; hl-block-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hl-block-mode.el

(autoload 'hl-block-mode "hl-block-mode" "\
Highlight block under the cursor.

This is a minor mode.  If called interactively, toggle the
`Hl-Block mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `hl-block-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'hl-block-global-mode 'globalized-minor-mode t)
(defvar hl-block-global-mode nil "\
Non-nil if Hl-Block-Global mode is enabled.
See the `hl-block-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `hl-block-global-mode'.")
(custom-autoload 'hl-block-global-mode "hl-block-mode" nil)
(autoload 'hl-block-global-mode "hl-block-mode" "\
Toggle Hl-Block mode in all buffers.
With prefix ARG, enable Hl-Block-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Hl-Block mode is enabled in all buffers where `hl-block--mode-turn-on'
would do it.

See `hl-block-mode' for more information on Hl-Block mode.

(fn &optional ARG)" t)
(register-definition-prefixes "hl-block-mode" '("hl-block-"))

;;; End of scraped data

(provide 'hl-block-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hl-block-mode-autoloads.el ends here
